### DISCUSSION TITLE
Addition of a monthly sensor

### DISCUSSION THREAD

**Discussion by Cliff-R-K** [faanskit/ha-checkwatt#42] [Ideas]
Do you have any plans on adding a "Current month net income" sensor ?

**Comment by faanskit** [comment]
Sorry, but no. For two reasons.

1. The request for revenue to EIB is very very slow and resource intense towards eib. We don't want to stress it more than we do 

2. All data will be available in HA over time to use native functions to make it happen. A simple template sensor can be made to accommodate this, or use the built in statistics card and you have it.

Having said that, if the need is big it can easily be done. The underlying pycheckwatt lib already supports it.

Anyway that's the rationale and no 1 is the one that worries me. We don't want Checkwatt tu shut us down...

/Marcus

**Comment by faanskit** [comment]
I hope you don t mind, but I converted this issue to a conversion.

**Comment by faanskit** [comment]
I have not tried it, but I think this should achieve what you want.
Please replace with the name of your daily sensor, and update as you see fit.
Please report back if it works

```yaml
automation:
  - alias: "Reset Monthly Sensor"
    trigger:
      platform: time
      at: "00:00:01"
    condition:
      condition: time
      weekday: 1  # This ensures it only triggers on the 1st day of the month
    action:
      service: sensor.set
      target:
        entity_id: sensor.checkwatt_monthly_monetary_sensor
      data:
        value: 0

  - alias: "Update Monthly Sensor"
    trigger:
      platform: time
      at: "23:59:00"
    action:
      service: sensor.set
      target:
        entity_id: sensor.checkwatt_monthly_monetary_sensor
      data_template:
        value: "{{ states('sensor.checkwatt_monthly_monetary_sensor') | float + states('sensor.checkwatt_daily_monetary_sensor') | float }}"

sensor:
  - platform: template
    sensors:
      checkwatt_monthly_monetary_sensor:
        friendly_name: "Checkwatt Monthly Net Income"
        unit_of_measurement: "Currency"  # Replace with your currency unit
        value_template: "{{ states('sensor.checkwatt_monthly_monetary_sensor') | float + states('sensor.checkwatt_daily_monetary_sensor') | float }}"

```
