### DISCUSSION TITLE
Publish to Google Sheets (Community)

### DISCUSSION THREAD

**Discussion by faanskit** [faanskit/ha-checkwatt#45] [Announcements]
The CheckWatt integration can be used to publish data to a [Community Google Spreadsheet](https://docs.google.com/spreadsheets/d/1zccKPgIVVHBvZUGvYNp4mlVlkNWyAiEGOLZtn4j_Ljs/edit?usp=sharing) and the [CheckWattRank](https://checkwattrank.netlify.app/) service.

This is done by configuring (and restarting) the integration. A browser refresh may be needed to these (Ctrl-F5) after upgrading the component.

![image](https://github.com/faanskit/ha-checkwatt/assets/10439868/2c7f2473-fd2d-4b1f-9d27-2df81af791e8)

**Alternatively**, this is done by adding data into `configurations.yaml` and `automations.yaml`.
This functionality requires that Extra Attributes and Energy Sensors are enabled.

**configuration.yaml**
REST function used to publish to the Community Google Spreadsheet.
```yaml
rest_command:
  publish_energy_data:
    url: 'https://checkwattrank.netlify.app/.netlify/functions/publishToSheet'
    method: 'POST'
    headers:
      Content-Type: 'application/json'
    payload: '{"display_name": "{{ display_name }}", "dso": "{{ dso }}", "electricity_company": "{{ electricity_company }}", "electricity_area": "{{electricity_area}}", "installed_power": {{ installed_power }}, "today_gross_income": {{ today_gross_income }}, "today_fee": {{ today_fee }}, "today_net_income": {{ today_net_income }}}'
```

**automations.yaml**
This sample automation pulls data from your sensors and publish them to Community Google Spreadsheet.
This example use an Input Button helper function to trigger the automation.

Replace sensor names as per your system.
```yaml
alias: Test Publish
description: ""
trigger:
  - platform: state
    entity_id:
      - input_button.publish
condition: []
action:
  - service: rest_command.publish_energy_data
    data:
      display_name: "{{state_attr('sensor.your_checkwatt_daily_yield', 'display_name')}}"
      dso: "{{state_attr('sensor.your_checkwatt_daily_yield', 'dso')}}"
      electricity_company: "{{state_attr('sensor.your_checkwatt_daily_yield', 'energy_provider')}}"
      electricity_area: "{{state_attr('sensor.your_spotpris_sensor', 'price_zone')}}"
      installed_power: "{{float(state_attr('sensor.your_checkwatt_daily_yield', 'charge_peak'))}}"
      today_gross_income: "{{float(state_attr('sensor.your_checkwatt_daily_yield', 'today_gross_income'))}}"
      today_fee: "{{float(state_attr('sensor.your_checkwatt_daily_yield', 'today_fees'))}}"
      today_net_income: "{{ states('sensor.your_checkwatt_daily_yield') }}"
mode: single

```
