### DISCUSSION TITLE
Current solar production?

### DISCUSSION THREAD

**Discussion by joelhell** [faanskit/ha-checkwatt#68] [Ideas]
Thanks for a great work! The integration is really usefull for me. Would it be difficult to also include a new sensor with current solar production in watt?

**Comment by faanskit** [comment]
This can be achieved with a Template Sensor, documented [here](https://github.com/faanskit/ha-checkwatt#use-templates).
The Battery SoC sensor has three power attributes:
- battery_power:
- grid_power:
- solar_power 

E.g. `sensor.xxx_battery_soc`
```yaml
state_class: measurement
battery_power: 420
grid_power: -420
solar_power: 0
charge_peak_ac: 12.3
charge_peak_dc: 12.3
discharge_peak_ac: 12.3
discharge_peak_dc: 12.3
monthly_grid_peak_power: 796
unit_of_measurement: "%"
attribution: Data provided by CheckWatt EnergyInBalance
device_class: battery
friendly_name: Xxx Battery SoC
```

Something like this in your `configuration.yaml`
```yaml
template:
  - sensor:
      - name: "CheckWatt Solar Power"
        unique_id: checkwatt_solar_power
        state: "{{ state_attr('sensor.xxx_battery_soc', 'solar_power')}}"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: total

```
