### ISSUE TITLE
Sensors 

### ISSUE THREAD

**Issue by Oooklart** [faanskit/ha-checkwatt#72]
I don’t know if it’s an issue or not but I can’t see live flow from grid, solar etc, just seeing total over time. It would be great to see production right now

**Comment by faanskit** [comment]
We do not intend to add power sensors to this integration, but the data is available to achieve what you want.
The Battery SoC sensors contains power attributes, e.g.:

```yaml
state_class: measurement
battery_power: -240
grid_power: -1740
solar_power: 1740
charge_peak_ac: 12.3
charge_peak_dc: 12.3
discharge_peak_ac: 12.3
discharge_peak_dc: 12.3
monthly_grid_peak_power: 446
unit_of_measurement: "%"
attribution: Data provided by CheckWatt EnergyInBalance
device_class: battery
friendly_name: Battery SoC

```
From this you can use templates in Home Assistant to created new sensors.
This is documented in the [Expert Section](https://github.com/faanskit/ha-checkwatt?tab=readme-ov-file#expert-section) in the documentation of the integration
